# Generated by Django 3.2 on 2023-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/время посещения'),
        ),
    ]
